apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
      - image: apache/activemq-artemis:latest-alpine
        name: activemq
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 8161
          name: http
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
