apiVersion: v1
kind: Service
metadata:
  name: activemq
  annotations:
    tailscale.com/expose: "true"
spec:
  ports:
  - port: 1883
    targetPort: 1883
    name: mqtt
  - port: 8161
    targetPort: 8161
    name: web
  selector:
    app: activemq
  type: LoadBalancer
